version: "3.7"

services:
  elasticsearch-01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    container_name: elasticsearch-01
    environment:
      - node.name=elasticsearch-01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=elasticsearch-02,elasticsearch-03
      - cluster.initial_master_nodes=elasticsearch-01,elasticsearch-02,elasticsearch-03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic
  elasticsearch-02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    container_name: elasticsearch-02
    environment:
      - node.name=elasticsearch-02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=elasticsearch-01,elasticsearch-03
      - cluster.initial_master_nodes=elasticsearch-01,elasticsearch-02,elasticsearch-03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - esdata02:/usr/share/elasticsearch/data
    networks:
      - elastic
  elasticsearch-03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    container_name: elasticsearch-03
    environment:
      - node.name=elasticsearch-03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=elasticsearch-01,elasticsearch-02
      - cluster.initial_master_nodes=elasticsearch-01,elasticsearch-02,elasticsearch-03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - esdata03:/usr/share/elasticsearch/data
    networks:
      - elastic
  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.2
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch-01:9200
      - XPACK_SECURITY_ENABLED=false
    ports:
      - 5601:5601
  fluentd:
    build:
      context: .
      dockerfile: Dockerfile-fluentd
    volumes:
      - ./_fluentd/etc:/fluentd/etc
      - nginxlog:/var/log/nginx:ro
    environment:
      - FLUENTD_CONF=fluent.conf
    ports:
      - 24224:24224
  nginx:
    image: nginx:stable
    volumes:
      - ./_nginx/etc/nginx.conf:/etc/nginx/nginx.conf:ro
      - nginxlog:/var/log/nginx
    ports:
      - 80:80
  go:
    build: .
    volumes:
      - .:/go/src/github.com/efkbook/blog-sample
    ports:
      - 8080:8080

volumes:
  esdata01:
    driver: local
  esdata02:
    driver: local
  esdata03:
    driver: local
  nginxlog:
    driver: local

networks:
  elastic:
    driver: bridge
