FROM debian:jessie

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get -qq update && apt-get install --no-install-recommends -y curl ca-certificates sudo build-essential libcurl4-gnutls-dev

# intall ruby
#RUN apt-get install -y \
#    git \
#    libssl-dev \
#    libreadline-dev \
#    zlib1g-dev

# install rbenv
#RUN git clone https://github.com/rbenv/rbenv.git ~/.rbenv && \
#    echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc && \
#    echo 'eval "$(rbenv int -)"' >> ~/.bashrc

#ENV PATH /root/.rbenv/shims:/root/.rbenv/bin:$PATH

# install ruby-build & ruby
#RUN git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build && \
#    ~/.rbenv/bin/rbenv install 2.6.3 && \
#    ~/.rbenv/bin/rbenv global 2.6.3

# initializa ruby encoding
#ENV RUBYOPT -EUTF-8

# RUN curl -L https://toolbelt.treasuredata.com/sh/install-debian-jessie-td-agent2.sh | sh
RUN curl -L https://toolbelt.treasuredata.com/sh/install-debian-jessie-td-agent3.sh | sh

# RUN /usr/sbin/td-agent-gem install fluent-plugin-elasticsearch fluent-plugin-record-reformer
RUN /usr/sbin/td-agent-gem install fluent-plugin-record-reformer
RUN /usr/sbin/td-agent-gem install fluent-plugin-elasticsearch

EXPOSE 24224

CMD exec td-agent -c /fluentd/etc/$FLUENTD_CONF -p /fluentd/plugins $FLUENTD_OPT
